---
# tasks file for apache
- name: update apt
  apt: update_cache=yes
- name: install apache2
  apt: name=apache2 state=latest
- name: create documrnt root
  file: path=/var/www/{{ server_name }} state=directory owner=www-data group=www-data
- name: setup index.html
  copy: src=index.html dest=/var/www/{{ server_name }} mode=0644 owner=www-data group=www-data

