- hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: create local users
      user:
        name: '{{ item }}'
        state: absent
        remove: true
      with_items: '{{ user_names }}'
